title: Quarantine Zone
description: Just a place to compile my wanderings
author: Scott Marshall
github: https://github.com/scottmarshall17
about: Just a place to compile my wanderings

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-github
      link: "https://github.com/smarshall17"

urls:
    - text: About Me
      url: /about/
    - text: My Projects
      url: /projects/

url: "smarshall17.github.io"
baseurl: "/quarantine-zone"
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
